### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by thecodechaser** [Debas-31/awesomebooks#7]
Feedbacks, suggestions, improvements.

**Comment by arnrdn** [comment]
Hello! I think your code is really good and you've done a great job!

**Comment by thecodechaser** [comment]
Hello, team @Debas-31  👋 

You did great so far, Your project is already looking great, You probably did hard work for this 👍. 

I have some suggestions for you, you can look into these changes 😄.

### Suggested Changes ♻️ 

- [ ] You can use pointer for navbar links
     Your navbar is perfect but I think you can add cursor: pointer property in your navbar links styling, It will make your link more visible and users can better understand that these are links.

Great job 👍
